export type Category = 'branding' | 'illustration' | 'ux-ui'

export interface Project {
  id: number
  slug: string
  category: Category
  categoryLabel: string
  categoryLabelEn: string
  title: string
  titleEn: string
  year: string
  desc: string
  descEn: string
  body: string[]
  bodyEn: string[]
  cover?: string
  coverPosition?: string
  images?: string[]
  videos?: string[]
  externalLink?: string
  testimonialRef?: { label: string; labelEn: string; href: string }
}

export const PROJECTS: Project[] = [
  {
    id: 7,
    slug: 'flaneur',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'Flaneur · Visuel identitet og kommunikation',
    titleEn: 'Flaneur · Visual Identity and Communication',
    year: '2024',
    desc: 'Visuel identitet, illustration og kommunikationsindhold for livsstilsbrandet Flaneur. Grafik, fotografering og SoMe-produktion.',
    descEn: 'Visual identity, illustration, and communication content for the lifestyle brand Flaneur. Graphics, photography, and social media production.',
    body: [
      'Flaneur er et livsstilsbrand med en stærk visuel profil. Opgaven bestod i at udvikle og producere grafisk indhold på tværs af print og digitale medier, herunder illustration, plakatdesign og produktfotografering.',
      'Arbejdet spændte fra tidlige skitser og idéudvikling til færdige leverancer til kampagnebrug. Illustrationerne og det fotografiske materiale er designet til at understøtte brandets udtryk på sociale medier og i trykte materialer.',
    ],
    bodyEn: [
      'Flaneur is a lifestyle brand with a distinctive visual profile. The project involved developing and producing graphic content across print and digital media, including illustration, poster design, and product photography.',
      'The work ranged from early sketches and concept development to finished deliverables for campaign use. The illustrations and photographic material were designed to support the brand\'s expression across social media and printed materials.',
    ],
    cover: '/projekter/Flaneur/A7402336.webp',
    images: [
      '/projekter/Flaneur/A7402379.webp',
      '/projekter/Flaneur/A7402407.webp',
      '/projekter/Flaneur/A7402427.webp',
      '/projekter/Flaneur/Body (1).webp',
      '/projekter/Flaneur/Body-kopi.webp',
      '/projekter/Flaneur/Untitled_Artwork 2.webp',
      '/projekter/Flaneur/Untitled_Artwork 4.webp',
      '/projekter/Flaneur/Skitsering af is-skilt.webp',
      '/projekter/Flaneur/White Orange  Pink Abstract Modern Illustrated Typographic Art Party Poster.webp',
      '/projekter/Flaneur/2.webp',
      '/projekter/Flaneur/3.webp',
      '/projekter/Flaneur/4.webp',
      '/projekter/Flaneur/6.webp',
    ],
  },
  {
    id: 8,
    slug: 'ba-afgangs-eksamen',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'Depositum · Bachelorafgangsprojekt',
    titleEn: 'Depositum · Bachelor Graduation Project',
    year: '2023',
    desc: 'Afgangsprojekt fra bacheloren i kommunikationsdesign på Designskolen Kolding. Bogdesign og visuel identitet for udgivelsen Depositum.',
    descEn: 'Graduation project from the BA in Communication Design at Designskolen Kolding. Book design and visual identity for the publication Depositum.',
    body: [
      'Depositum er resultatet af afgangsprojektet fra bacheloren i kommunikationsdesign på Designskolen Kolding, 2023. Projektet udmundede i design og produktion af en bog, hvor typografi, layout og det visuelle udtryk er udviklet fra bunden.',
      'Bogens identitet er bygget op om en stærk formsprogslig linje, der følger publikationen fra omslag til bagside. Det samlede design behandler bogen som et autonomt objekt med en sammenhængende visuel fortælling.',
    ],
    bodyEn: [
      'Depositum is the result of the graduation project from the BA in Communication Design at Designskolen Kolding, 2023. The project resulted in the design and production of a book, with typography, layout, and visual language developed from scratch.',
      'The book\'s identity is built around a coherent formal language that runs throughout the publication from cover to back. The overall design treats the book as an autonomous object with a unified visual narrative.',
    ],
    cover: '/projekter/BA afgangs-eksamen/Bogen-foto.webp',
    coverPosition: 'object-[center_23%]',
    images: [
      '/projekter/BA afgangs-eksamen/Bogen-foto.webp',
      '/projekter/BA afgangs-eksamen/Bogen depositum omslaget.webp',
      '/projekter/BA afgangs-eksamen/Bogen depositum omslag.webp',
      '/projekter/BA afgangs-eksamen/Bogen depositum bagside.webp',
      '/projekter/BA afgangs-eksamen/portfolio-1.webp',
      '/projekter/BA afgangs-eksamen/353676027_656944882560552_4102170183199640948_n.webp',
    ],
    testimonialRef: {
      label: 'Se legatudtalelse fra HK/Privats Ophavsretsfond →',
      labelEn: 'See grant reference from HK/Privats Ophavsretsfond →',
      href: '/cv/udtalelser?i=6',
    },
  },
  {
    id: 26,
    slug: 'piba',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'PIBA · Visuel præsentation',
    titleEn: 'PIBA · Visual Presentation',
    year: '2025',
    desc: 'Visuel identitet og præsentationsmateriale for PIBA.',
    descEn: 'Visual identity and presentation material for PIBA.',
    body: [
      'Visuel identitet og præsentationsmateriale for PIBA. Projektet dækkede design af præsentationsslides og grafiske materialer til brug i kommunikation og markedsføring.',
    ],
    bodyEn: [
      'Visual identity and presentation material for PIBA. The project covered the design of presentation slides and graphic materials for use in communication and marketing.',
    ],
    cover: '/projekter/piba/2.png',
    coverPosition: 'object-[center_33%]',
    images: [
      '/projekter/piba/2.png',
      '/projekter/piba/3.png',
      '/projekter/piba/4.png',
      '/projekter/piba/5.png',
      '/projekter/piba/6.webp',
      '/projekter/piba/7.png',
      '/projekter/piba/8.webp',
      '/projekter/piba/9.png',
      '/projekter/piba/10.png',
      '/projekter/piba/11.png',
      '/projekter/piba/A_highly_refined,_editorial-style_product_202606271335.jpeg',
    ],
    videos: [
      '/projekter/piba/Video design.mp4',
    ],
  },
  {
    id: 10,
    slug: 'lp-cover',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'Hifalutin Lowly · LP-coverdesign',
    titleEn: 'Hifalutin Lowly · LP Cover Design',
    year: '2023',
    desc: 'Konceptudvikling og coverdesign til LP-udgivelse med tredimensionelle, metalliske renders.',
    descEn: 'Concept development and cover design for an LP release using three-dimensional metallic renders.',
    body: [
      'Coverdesign til LP-udgivelsen "Hifalutin Lowly" udviklet med udgangspunkt i tredimensionelle, metalliske CGI-renders. Konceptet bygger på et strejf af sci-fi og industriel æstetik, der afspejler musikkens karakter og kunstnerens visuelle univers.',
      'De digitalt renderede former er arrangeret i et typografisk layout, der giver plads til albummets titel og kunstnernavn uden at forstyrre den visuelle dramaturgi. Coveret er designet i både digital og trykoptimeret version.',
    ],
    bodyEn: [
      'Cover design for the LP release "Hifalutin Lowly", developed around three-dimensional metallic CGI renders. The concept draws on a sci-fi and industrial aesthetic that reflects the character of the music and the artist\'s visual universe.',
      'The digitally rendered forms are arranged in a typographic layout that accommodates the album title and artist name without interrupting the visual dramaturgy. The cover is designed in both digital and print-optimised versions.',
    ],
    cover: '/projekter/LP-Cover/lp2.webp',
    images: [
      '/projekter/LP-Cover/lp2.webp',
      '/projekter/LP-Cover/Plade8.webp',
      '/projekter/LP-Cover/portfolio-1.webp',
    ],
  },
  {
    id: 11,
    slug: 'komunale-losninger',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'Podcast Cover · Kommunale Løsninger',
    titleEn: 'Podcast Cover · Municipal Solutions',
    year: '2023',
    desc: 'Coverdesign og illustration til podcast om kommunale løsninger og bæredygtighed.',
    descEn: 'Cover design and illustration for a podcast on municipal solutions and sustainability.',
    body: [
      'Projekt med visuel identitet og illustration til en podcast om kommunale løsninger og bæredygtighed. Illustrationerne er tegnet med en let, humoristisk streg der gør komplekse emner tilgængelige og indbydende for et bredt publikum.',
      'Coverdesignet kombinerer en stærk typografisk linje med de håndtegnede illustrationer og bygger en visuel bro mellem det officielle og det folkelige. Farvepaletten er frisk og åben og afspejler de offentlige rums natur og funktion.',
    ],
    bodyEn: [
      'Project combining visual identity and illustration for a podcast about municipal solutions and sustainability. The illustrations are drawn with a light, humorous line that makes complex topics accessible and inviting to a broad audience.',
      'The cover design combines a strong typographic line with the hand-drawn illustrations, building a visual bridge between the official and the everyday. The colour palette is fresh and open, reflecting the nature and function of public spaces.',
    ],
    cover: '/projekter/To fluer med et smæk/Kopi af Skærmbillede 2022-12-06 kl. 15.31.05.webp',
    images: [
      '/projekter/To fluer med et smæk/Kopi af Skærmbillede 2022-12-06 kl. 15.31.05.webp',
    ],
  },
  {
    id: 12,
    slug: 'sportx',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'SportX · Identitetsdesign og SoMe',
    titleEn: 'SportX · Identity Design and Social Media',
    year: '2023',
    desc: 'Visuel identitet og social media-indhold for sports- og teknologibrandet SportX med mørk, neonfarvet æstetik.',
    descEn: 'Visual identity and social media content for sports and technology brand SportX with a dark, neon-coloured aesthetic.',
    body: [
      'SportX er et sports- og teknologibrand med en distinkt visuel identitet baseret på sort baggrund og neongrønne accentfarver. Projektet dækkede konceptudvikling, identitetsdesign og produktion af social media-indhold.',
      'Indholdet er designet til at skille sig ud i et feed domineret af lyse, traditionelle sportsbrands. Den mørke æstetik og de skarpe neonfarver giver SportX et futuristisk, digitalt udtryk der taler til en ung, sportsinteresseret målgruppe.',
    ],
    bodyEn: [
      'SportX is a sports and technology brand with a distinctive visual identity based on black backgrounds and neon green accent colours. The project covered concept development, identity design, and social media content production.',
      'The content is designed to stand out in a feed dominated by bright, traditional sports brands. The dark aesthetic and sharp neon colours give SportX a futuristic, digital look that speaks to a young, sports-interested audience.',
    ],
    cover: '/projekter/SportX/portfolio-1.webp',
    images: ['/projekter/SportX/portfolio-1.webp'],
  },
  {
    id: 13,
    slug: 'aarhus-bornehojskole',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'Aarhus Børnehøjskole · Identitetsdesign',
    titleEn: 'Aarhus Children\'s Højskole · Identity Design',
    year: '2023',
    desc: 'Komplet visuel identitet, kataloger og trykmateriale for Aarhus Børnehøjskole.',
    descEn: 'Complete visual identity, catalogues, and print materials for Aarhus Children\'s Højskole.',
    body: [
      'Visuel identitet for Aarhus Børnehøjskole, en institution med fokus på kreativitet og fællesskab for børn. Opgaven var at skabe en sammenhængende identitet der fremstår venlig og indbydende uden at miste professionalisme og troværdighed.',
      'Identitetssystemet er bygget op om en varm farvepalette, en rund og tilgængelig typografi og fleksible grafiske elementer der fungerer på tværs af plakater, brochurer og digitale flader. Kataloget og bannerdesignet anvender systemet til fulde og viser spændvidden i det visuelle udtryk.',
    ],
    bodyEn: [
      'Visual identity for Aarhus Children\'s Højskole, an institution focused on creativity and community for children. The task was to create a cohesive identity that feels friendly and inviting without losing professionalism and credibility.',
      'The identity system is built around a warm colour palette, a rounded and accessible typeface, and flexible graphic elements that work across posters, brochures, and digital surfaces. The catalogue and banner design deploy the system in full, demonstrating the range of the visual language.',
    ],
    cover: '/projekter/Aarhus Bornehojskole/DSCF9283.webp',
    images: [
      '/projekter/Aarhus Bornehojskole/DSCF9282.webp',
      '/projekter/Aarhus Bornehojskole/DSCF9283.webp',
      '/projekter/Aarhus Bornehojskole/DSCF9297.webp',
      '/projekter/Aarhus Bornehojskole/Katalog-1.webp',
      '/projekter/Aarhus Bornehojskole/Katalog-3.webp',
      '/projekter/Aarhus Bornehojskole/Katalog-5.webp',
      '/projekter/Aarhus Bornehojskole/Katalog-6.webp',
      '/projekter/Aarhus Bornehojskole/Katalog-7.webp',
      '/projekter/Aarhus Bornehojskole/Katalog-8.webp',
      '/projekter/Aarhus Bornehojskole/portfolio-1.webp',
    ],
  },
  {
    id: 14,
    slug: 'digitale-illustrationer',
    category: 'illustration',
    categoryLabel: 'Illustration',
    categoryLabelEn: 'Illustration',
    title: 'Digitale malerier og tegninger',
    titleEn: 'Digital Paintings and Drawings',
    year: '2022',
    desc: 'Et udvalg af digitale malerier og tegninger produceret til projekter og som selvstændige arbeider.',
    descEn: 'A selection of digital paintings and drawings produced for projects and as autonomous works.',
    body: [
      'En samling digitale malerier og tegninger skabt i Procreate og Adobe Illustrator. Arbejderne spænder fra skitseagtige, ekspressive udtryk til mere gennemarbejdede kompositioner og dækker genrer som portræt, natur og abstrakt.',
      'Illustrationerne er produceret dels som kommercielle arbeider til konkrete projekter, dels som personlige eksperimenter med digitale medier og teknikker. Serien viser bredden i den digitale illustrationspraksis.',
    ],
    bodyEn: [
      'A collection of digital paintings and drawings created in Procreate and Adobe Illustrator. The works span from sketch-like expressive expressions to more considered compositions, covering genres such as portrait, nature, and abstract.',
      'The illustrations were produced partly as commercial works for specific projects and partly as personal experiments with digital media and techniques. The series demonstrates the breadth of the digital illustration practice.',
    ],
    cover: '/projekter/Digitale Illustrationer/portfolio-1.webp',
    images: [
      '/projekter/Digitale Illustrationer/portfolio-1.webp',
      '/projekter/Digitale Illustrationer/portfolio-2.webp',
      '/projekter/Digitale Illustrationer/portfolio-3.webp',
      '/projekter/Digitale Illustrationer/portfolio-4.webp',
    ],
  },
  {
    id: 15,
    slug: 'vid-sans',
    category: 'illustration',
    categoryLabel: 'Illustration',
    categoryLabelEn: 'Illustration',
    title: 'Vid&Sans · Redaktionel illustration og layout',
    titleEn: 'Vid&Sans · Editorial Illustration and Layout',
    year: '2022',
    desc: 'Illustration, collage og layoutdesign til det redaktionelle magasin Vid&Sans.',
    descEn: 'Illustration, collage, and layout design for the editorial magazine Vid&Sans.',
    body: [
      'Vid&Sans er et redaktionelt magasin med fokus på filosofi, tænkning og samfund. Opgaven bestod i at skabe illustrationer og layoutdesign til udgivelserne, herunder portræt-illustrationer af filosoffer og tænkere samt collager til artikelbrug.',
      'Illustrationerne er tegnet med en skitseret, grafisk streg og formidler komplekse idéer i et visuelt tilgængeligt format. Layoutet balancerer det teksttunge indhold med billeder og grafiske elementer der guider læseren gennem magasinets sektioner.',
    ],
    bodyEn: [
      'Vid&Sans is an editorial magazine focused on philosophy, thought, and society. The task involved creating illustrations and layout design for the publications, including portrait illustrations of philosophers and thinkers as well as collages for article use.',
      'The illustrations are drawn with a sketchy, graphic line and communicate complex ideas in a visually accessible format. The layout balances the text-heavy content with images and graphic elements that guide the reader through the magazine\'s sections.',
    ],
    cover: '/projekter/Vid&Sans/DSCF9350.webp',
    externalLink: 'https://vidogsans.dk/',
    images: [
      '/projekter/Vid&Sans/DSCF9338.webp',
      '/projekter/Vid&Sans/DSCF9350.webp',
      '/projekter/Vid&Sans/DSCF9370.webp',
      '/projekter/Vid&Sans/filosof.webp',
      '/projekter/Vid&Sans/Pirre.webp',
      '/projekter/Vid&Sans/portfolio-1.webp',
    ],
  },
  {
    id: 18,
    slug: 'kfum-kfuk',
    category: 'illustration',
    categoryLabel: 'Illustration',
    categoryLabelEn: 'Illustration',
    title: 'KFUM&KFUK · Illustration til børnemagasin',
    titleEn: 'KFUM&KFUK · Illustration for Children\'s Magazine',
    year: '2022',
    desc: 'Illustrationer og konceptdesign til børnemagasin for KFUM&KFUK, herunder "find fem fejl"-illustration.',
    descEn: 'Illustrations and concept design for the KFUM&KFUK children\'s magazine, including a spot-the-difference illustration.',
    body: [
      'Illustrationer og konceptdesign til børnemagasinet for KFUM&KFUK. Opgaven bestod i at skabe levende, farvestrålende illustrationer der appellerer til børn og understøtter organisationens legende og inkluderende tone.',
      'Leverancerne inkluderede en serie ikoner og elementer til redaktionel brug samt en helsidesillustration i formatet "Find fem fejl" med MGP-tema. Illustrationerne er tegnet i en frisk, blid stil der passer til målgruppen og mediets format.',
    ],
    bodyEn: [
      'Illustrations and concept design for the KFUM&KFUK children\'s magazine. The task involved creating vibrant, colourful illustrations that appeal to children and support the organisation\'s playful and inclusive tone.',
      'Deliverables included a series of icons and elements for editorial use and a full-page spot-the-difference illustration with an MGP theme. The illustrations are drawn in a fresh, gentle style that suits the audience and the format of the medium.',
    ],
    cover: '/projekter/KFUM-KFUK/DSCF9305.webp',
    images: [
      '/projekter/KFUM-KFUK/DSCF9305.webp',
      '/projekter/KFUM-KFUK/DSCF9321.webp',
      '/projekter/KFUM-KFUK/DSCF9353.webp',
      '/projekter/KFUM-KFUK/portfolio-1.webp',
    ],
  },
  {
    id: 21,
    slug: 'ramtt',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'RAMTT · Identitetsdesign',
    titleEn: 'RAMTT · Identity Design',
    year: '2023',
    desc: 'Visuel identitet for sportsbrandet RAMTT med fokus på kraft, bevægelse og atletisme.',
    descEn: 'Visual identity for the sports brand RAMTT focused on power, movement, and athleticism.',
    body: [
      'RAMTT er et sportsbrand med en aggressiv, dynamisk visuel identitet. Opgaven var at skabe et logo og et farvesystem der kan bæres på tværs af discipliner — fra løb til kampsporten — og stadig fremstå sammenhængende og stærkt.',
      'Logoet fungerer i en enkelt farve mod et monokromt fotografi såvel som i et system af farvevariantioner der giver fleksibilitet på tværs af beklædning, digitale flader og event-branding. Resultatet er en identitet der bærer sportens intensitet ind i det grafiske udtryk.',
    ],
    bodyEn: [
      'RAMTT is a sports brand with an aggressive, dynamic visual identity. The task was to create a logo and colour system that could carry across disciplines — from running to combat sports — while remaining cohesive and powerful.',
      'The logo works in a single colour against monochrome photography as well as in a system of colour variants that provides flexibility across apparel, digital surfaces, and event branding. The result is an identity that brings the intensity of sport into the graphic expression.',
    ],
    cover: '/projekter/RAMTT/Ramtt design (1).webp',
    images: [
      '/projekter/RAMTT/Ramtt design (1).webp',
      '/projekter/RAMTT/Ramtt Multi-design.webp',
      '/projekter/RAMTT/Ramtt design (2).webp',
      '/projekter/RAMTT/Ramtt design (4).webp',
      '/projekter/RAMTT/Ramtt Multi-design (2).webp',
      '/projekter/RAMTT/Ramtt Multi-design (3).webp',
    ],
  },
  {
    id: 22,
    slug: 'suhn-io',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'SUHN 10© · Branding og emballagedesign',
    titleEn: 'SUHN 10© · Branding and Packaging Design',
    year: '2024',
    desc: 'Visuel identitet og emballagedesign for sportsernæringsbrandet SUHN 10© med sølv/chrome æstetik og tøjlinje.',
    descEn: 'Visual identity and packaging design for sports nutrition brand SUHN 10© with a silver/chrome aesthetic and apparel line.',
    body: [
      'SUHN 10© er et sportsernæringsbrand med en distinkt, teknologisk visuel identitet. Emballagedesignet for gelportionerne kombinerer et sølv metallic finish med lyseblå typografi og skarpe produktinformationer i et udtryk der skiller sig ud på hylden og kommunikerer effektivitet og kvalitet.',
      'Projektet udstrakte sig fra emballagen til en beklædningslinje med hoodie og øvrige produkter. Den grafiske tone er minimalistisk men præcis og fungerer konsistent på tværs af det fysiske produkt og digitale flade.',
    ],
    bodyEn: [
      'SUHN 10© is a sports nutrition brand with a distinctive, technological visual identity. The packaging design for the gel portions combines a silver metallic finish with light blue typography and sharp product information in an expression that stands out on the shelf and communicates efficiency and quality.',
      'The project extended from the packaging to an apparel line including hoodies and other products. The graphic tone is minimalist but precise, and functions consistently across the physical product and digital surfaces.',
    ],
    cover: '/projekter/SUHN io/Visuel Præsentation SUHN io.webp',
    images: [
      '/projekter/SUHN io/Visuel Præsentation SUHN io.webp',
      '/projekter/SUHN io/Visuel Præsentation SUHN io (1).webp',
      '/projekter/SUHN io/visuel præsentation - SUHN io (3).webp',
      '/projekter/SUHN io/13.webp',
      '/projekter/SUHN io/18.webp',
      '/projekter/SUHN io/15.webp',
      '/projekter/SUHN io/færdig Brandguide SUHN IO.webp',
      '/projekter/SUHN io/færdig Brandguide SUHN IO (1).webp',
      '/projekter/SUHN io/færdig Brandguide SUHN IO (2).webp',
      '/projekter/SUHN io/A_clean_editorialstyle_portrait_a_female_cyclist_i_e2989d6099.webp',
      '/projekter/SUHN io/Refill_plastic_container_with_pump_202605200308.webp',
    ],
    videos: [
      '/projekter/SUHN io/Visuel præsentation SUHN IO.mp4',
      '/projekter/SUHN io/Visuel præsentation SUHN IO (1).mp4',
    ],
  },
  {
    id: 23,
    slug: 'grafisk-bog',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'Grafisk opsætning og design af bog',
    titleEn: 'Graphic Layout and Book Design',
    year: '2023',
    desc: 'Konceptudvikling og grafisk opsætning af bog med klassisk nordisk udtryk.',
    descEn: 'Concept development and graphic layout of a book with a classic Nordic expression.',
    body: [
      'Bogdesign med udgangspunkt i en klassisk nordisk æstetik. Konceptudviklingen tog afsæt i referencebilleder fra dansk designhistorie og nordisk boghåndværk og omsatte disse til en sammenhængende visuel retning for layout, typografi og materialevalg.',
      'Designet er bygget op om en jordnær farvepalette, gode papirkvaliteter og en typografisk linje der balancerer elegance og læselighed. Resultatet er et boglayout der fremstår håndgjort og gennemtænkt.',
    ],
    bodyEn: [
      'Book design based on a classic Nordic aesthetic. The concept development drew on reference images from Danish design history and Nordic book craftsmanship, translating these into a cohesive visual direction for layout, typography, and material choices.',
      'The design is built around an earthy colour palette, quality paper stocks, and a typographic line that balances elegance and legibility. The result is a book layout that feels handcrafted and considered.',
    ],
    cover: '/projekter/Grafisk opsætning og design af bog/Skærmbillede 2023-10-04 kl. 16.01.20.webp',
    images: [
      '/projekter/Grafisk opsætning og design af bog/Skærmbillede 2023-10-04 kl. 16.00.26.webp',
      '/projekter/Grafisk opsætning og design af bog/Skærmbillede 2023-10-04 kl. 16.01.04.webp',
      '/projekter/Grafisk opsætning og design af bog/Skærmbillede 2023-10-04 kl. 16.01.20.webp',
      '/projekter/Grafisk opsætning og design af bog/Skærmbillede 2023-10-04 kl. 16.01.30.webp',
    ],
  },
  {
    id: 5,
    slug: 'velo-magazine',
    category: 'illustration',
    categoryLabel: 'Illustration',
    categoryLabelEn: 'Illustration',
    title: 'Velo Magazine · Editorial illustration',
    titleEn: 'Velo Magazine · Editorial Illustration',
    year: '2024',
    desc: 'Månedlige illustrationer til cykelmagasin med portræt og editorial karakter.',
    descEn: 'Monthly illustrations for a cycling magazine, with a portrait and editorial character.',
    cover: '/projekter/VeloMore Magazine/Cort.webp',
    body: [
      'En løbende serie af editorial-illustrationer produceret til et nichebladet om cykelkultur. Serien spænder over portræt, reportage og konceptuelle illustrationer og dækker både velkendte profiler fra professionel cykelsport og stemningsbilleder fra kulturen rundt om sporten.',
      'Illustrationerne kombinerer håndtegnet karakter med digital finish og er designet til at fungere som selvstændige billedarbeider i sammenhæng med den redaktionelle tekst. Hvert motiv er tilpasset det aktuelle nummers tema og den givne produktionstidsramme.',
    ],
    bodyEn: [
      'An ongoing series of editorial illustrations produced for a niche cycling culture magazine. The series spans portrait, reportage, and conceptual illustration, covering both well-known faces from professional cycling and atmospheric images from the culture surrounding the sport.',
      'The illustrations combine a hand-drawn quality with digital finish and are designed to stand as independent image works alongside the editorial text. Each piece is tailored to the theme of the current issue and its production schedule.',
    ],
    images: [
      '/projekter/VeloMore Magazine/Cort.webp',
      '/projekter/VeloMore Magazine/Lund.webp',
    ],
  },
  {
    id: 19,
    slug: 'jesus-would-bike',
    category: 'branding',
    categoryLabel: 'Branding',
    categoryLabelEn: 'Branding',
    title: 'Jesus Would Bike · Plakatkonkurrence',
    titleEn: 'Jesus Would Bike · Poster Competition',
    year: '2022',
    desc: 'Vindende plakat til Tour de France 2022-plakatkonkurrence. Typografisk plakat i mørk æstetik med neon og metalliske elementer.',
    descEn: 'Winning poster entry for the Tour de France 2022 poster competition. Typographic poster with a dark aesthetic featuring neon and metallic elements.',
    body: [
      '"Jesus Would Bike" er en typografisk plakat skabt til en plakatkonkurrence i samarbejde med Tour de France 2022. Plakaten endte blandt vinderne og er efterfølgende vist i digital wild posting-format.',
      'Konceptet tager udgangspunkt i en irisk provokation: hvad ville Jesus køre? Svaret er cyklen, og det visuelle udtryk understeger pointen med en mørk, rå æstetik bygget op om gotisk typografi, neonfarver og metalliske grafiske elementer. Resultatet er en plakat der skiller sig markant ud i det visuelle rum.',
    ],
    bodyEn: [
      '"Jesus Would Bike" is a typographic poster created for a poster competition in collaboration with Tour de France 2022. The poster was among the winners and has since been shown in digital wild posting format.',
      'The concept is built on a provocative premise: what would Jesus ride? The answer is the bicycle, and the visual expression underlines the point with a dark, raw aesthetic built around Gothic typography, neon colours, and metallic graphic elements. The result is a poster that stands out sharply in the visual landscape.',
    ],
    cover: '/projekter/Jesus Would Bike/portfolio-1.webp',
    images: [
      '/projekter/Jesus Would Bike/portfolio-1.webp',
      '/projekter/Jesus Would Bike/296866110_1242781503143108_8321429921132289341_n.webp',
    ],
  },
  {
    id: 20,
    slug: 'videnskab-podcast',
    category: 'branding',
    categoryLabel: 'Illustration',
    categoryLabelEn: 'Illustration',
    title: 'Videnskab.dk · Podcast Brand Guide',
    titleEn: 'Videnskab.dk · Podcast Brand Guide',
    year: '2024',
    desc: 'Visuel identitet og brand guide for Videnskab.dk podcast. Coverdesign, farvepalette og typografiske retningslinjer.',
    descEn: 'Visual identity and brand guide for Videnskab.dk podcast. Cover design, colour palette, and typographic guidelines.',
    body: [
      'Brand guide og coverdesign til Videnskab.dk podcast. Opgaven bestod i at udvikle en sammenhængende visuel identitet der kommunikerer faglighed og tilgængelighed på samme tid.',
      'Guiden definerer farvepalet, typografi og grafiske elementer til brug på tværs af podcast-platformerne. Coverdesignet er produceret i flere størrelser til Apple Podcasts, Spotify og sociale medier.',
    ],
    bodyEn: [
      'Brand guide and cover design for Videnskab.dk podcast. The task was to develop a cohesive visual identity that communicates both expertise and accessibility.',
      'The guide defines colour palette, typography, and graphic elements for use across podcast platforms. The cover design was produced in multiple sizes for Apple Podcasts, Spotify, and social media.',
    ],
    externalLink: 'https://videnskab.dk/',
    cover: '/projekter/Videnskab.dk Podcast/Cover_size3.webp',
    images: [
      '/projekter/Videnskab.dk Podcast/Cover_size3.webp',
      '/projekter/Videnskab.dk Podcast/Cover_size4.webp',
      '/projekter/Videnskab.dk Podcast/RGB_HudlægensBord_Logo_1400px1400p.webp',
    ],
  },
  {
    id: 21,
    slug: 'substrate',
    category: 'ux-ui',
    categoryLabel: 'UX · UI',
    categoryLabelEn: 'UX · UI',
    title: 'Substrate · Branding og digital identitet',
    titleEn: 'Substrate · Branding and Digital Identity',
    year: '2025',
    desc: 'Visuel identitet og digital præsentation for Substrate. Logodesign, brandguide og mobilpræsentation.',
    descEn: 'Visual identity and digital presentation for Substrate. Logo design, brand guide, and mobile presentation.',
    body: [
      'Substrate er et digitalt produkt med en klar og minimalistisk visuel profil. Projektet omfattede udvikling af logo, brandguide og en komplet digital identitet tilpasset et moderne tech-udtryk.',
      'Den visuelle præsentation er bygget op om klarhed og enkelhed — et udtryk der kommunikerer troværdighed og teknisk præcision. Den mobile præsentation demonstrerer identiteten i praksis på tværs af digitale platforme.',
    ],
    bodyEn: [
      'Substrate is a digital product with a clear and minimalist visual profile. The project involved developing a logo, brand guide, and complete digital identity tailored to a modern tech aesthetic.',
      'The visual presentation is built on clarity and simplicity — an expression that communicates credibility and technical precision. The mobile presentation demonstrates the identity in practice across digital platforms.',
    ],
    cover: '/projekter/Substrate/Substrate Delt Presentation (3).webp',
    images: [
      '/projekter/Substrate/Substrate Delt Presentation (1).webp',
      '/projekter/Substrate/Substrate Delt Presentation (2).webp',
      '/projekter/Substrate/Substrate Delt Presentation (3).webp',
      '/projekter/Substrate/Substrate Delt Presentation (4).webp',
      '/projekter/Substrate/Substrate Delt Presentation (5).webp',
      '/projekter/Substrate/Substrate Delt Presentation (6).webp',
      '/projekter/Substrate/sub.webp',
      '/projekter/Substrate/Substraete New Logo (1).webp',
    ],
    videos: ['/projekter/Substrate/Færdig Mobile Video.mp4'],
  },
  {
    id: 25,
    slug: 'gobik',
    category: 'branding',
    categoryLabel: 'Illustration',
    categoryLabelEn: 'Illustration',
    title: 'GOBIK · Cykeltrøjedesign',
    titleEn: 'GOBIK · Cycling Jersey Design',
    year: '2024',
    desc: 'Design af cykeltrøje med blomstermotiv til GOBIK. Illustration, mønsterdesign og mockup-fotografering.',
    descEn: 'Cycling jersey design with floral motif for GOBIK. Illustration, pattern design, and mockup photography.',
    body: [
      'Designet af en cykeltrøje med et blomstermotiv — specifikt solsikker — som det bærende grafiske element. Illustrationen er tegnet til at omfavne trøjens form og følge kroppens bevægelse i sadlen.',
      'Projektet dækkede hele processen fra idé og illustration til det færdige mockup, der viser trøjen på kroppen i realistisk kontekst. De AI-assisterede mockup-fotografier viser trøjedesignet fra forskellige vinkler og i bevægelse.',
    ],
    bodyEn: [
      'Design of a cycling jersey with a floral motif — specifically sunflowers — as the central graphic element. The illustration is drawn to embrace the jersey\'s form and follow the body\'s movement in the saddle.',
      'The project covered the entire process from concept and illustration to the finished mockup, showing the jersey on the body in a realistic context. The AI-assisted mockup photographs show the jersey design from different angles and in motion.',
    ],
    cover: '/projekter/GOBIK cykeltrøje/Person seated Jun 26 17.19.webp',
    images: [
      '/projekter/GOBIK cykeltrøje/Person seated Jun 26 17.19.webp',
      '/projekter/GOBIK cykeltrøje/Solsikker.webp',
      '/projekter/GOBIK cykeltrøje/IMG_0234.webp',
      '/projekter/GOBIK cykeltrøje/IMG_0240.webp',
      '/projekter/GOBIK cykeltrøje/A_highly_cinematic_luxury_sportswear_202606261827.webp',
      '/projekter/GOBIK cykeltrøje/Tightly Framed Front Torso Jun 26 2026.webp',
      '/projekter/GOBIK cykeltrøje/Shot_from_behind_with_a_202606261753.webp',
      '/projekter/GOBIK cykeltrøje/35mm Lens Capture Jun 26 17-19.webp',
      '/projekter/GOBIK cykeltrøje/lav_bukserne_sorte_202606261746.webp',
    ],
  },
  {
    id: 9,
    slug: 'booklab',
    category: 'branding',
    categoryLabel: 'Fotografi',
    categoryLabelEn: 'Photography',
    title: 'BookLab · Bogfotografering',
    titleEn: 'BookLab · Book Photography',
    year: '2023',
    desc: 'Fotografering og billedredigering af bøger til redaktionelt og kommercielt brug.',
    descEn: 'Photography and editing of books for editorial and commercial use.',
    body: [
      'BookLab er et projekt om fotografering af bøger som selvstændige objekter. Opgaven var at skabe stemningsfulde, atmosfæriske billeder der fremhæver bogens materialitet og visuelle udtryk frem for blot at dokumentere indholdet.',
      'Billederne er designet til redaktionel og kommerciel brug og er produceret med naturligt lys og enkle rekvisitter der understøtter bogens identitet uden at konkurrere med den.',
    ],
    bodyEn: [
      'BookLab is a project about photographing books as autonomous objects. The task was to create atmospheric, evocative images that highlight the materiality and visual expression of the book rather than simply documenting its contents.',
      'The images are designed for editorial and commercial use and were produced with natural light and simple props that support the book\'s identity without competing with it.',
    ],
    cover: '/projekter/BookLab/portfolio-1.webp',
    images: ['/projekter/BookLab/portfolio-1.webp'],
    videos: ['/projekter/BookLab/download.mp4'],
  },
]
